apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-flexric
data:
  flexric.conf: |
      [NEAR-RIC]
      NEAR_RIC_IP = @FLEXRIC_IP@
      [XAPP]
      DB_PATH = /flexric/db/
      DB_NAME = xapp_rnis_db
     